steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "services/api/Dockerfile",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ai-prophet-api-shared:latest",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ai-prophet-api-shared:latest",
      ]

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ai-prophet-api-shared:latest"
